[package]
name = "rafa/template"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
Cmdr = "evaera/cmdr@1.12.0"
Replica = "aykut92/replica@0.1.7"
Janitor = "howmanysmall/janitor@1.17.0"
Signal = "stravant/goodsignal@0.2.1"
Shake = "sleitnick/shake@1.1.0"
OctoTree = "sleitnick/octo-tree@0.3.1"
React = "jsdotlua/react@17.0.2"
ReactRoblox = "jsdotlua/react-roblox@17.0.2"
ReactRodux = "solarhorizon/react-rodux@0.2.2"
Rodux = "roblox/rodux@3.0.0"
Flipper = "reselim/flipper@2.0.0"
Charm = "littensy/charm@0.1.0"
BoatTween = "boatbomber/boattween@1.0.1"
QuadTree = "nightcycle/quad-tree@0.1.2"
HashLib = "boatbomber/hashlib@1.0.0"
UILabs = "pepeeltoro41/ui-labs@2.3.5"
SmartBone = "jakeywastaken/smartbone-2@0.4.2"
WindLines = "aspecky/windlines@1.0.0"
ObjectCache = "pyseph/objectcache@1.4.6"
